#!/bin/bash
echo "------------------   $1"
case "$1" in
   "c") bash ./C > output
   ;;
   "java") bash ./JAVA > output
   ;;
   "python") bash ./PYTHON > output
   ;;
   *) bash C > output
      bash JAVA >> output
      bash PYTHON >> output
   ;;
esac
output = cat ./output
search = "language"
sed -i "s/"language"/"$output"/" ./index.html
# mv index.txt index.html
# export output = cat ./output
# index.html contain $output then change 

