#!/bin/bash
echo "------------------   $1"
case "$1" in
   "c") bash ./C
   ;;
   "java") bash ./JAVA
   ;;
   "python") bash ./PYTHON
   ;;
   *) bash C
      bash JAVA
      bash PYTHON
   ;;
esac

